//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRIStockSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RRIStockSystemDBEntities : DbContext
    {
        public RRIStockSystemDBEntities()
            : base("name=RRIStockSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Product> T_Product { get; set; }
        public virtual DbSet<T_Stock> T_Stock { get; set; }
        public virtual DbSet<T_Variety> T_Variety { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<V_User> V_User { get; set; }
        public virtual DbSet<T_ApplicationLog> T_ApplicationLog { get; set; }
    }
}
