//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRIStockSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Stock
    {
        public System.Guid ID { get; set; }
        public System.Guid FK_Product { get; set; }
        public System.DateTime StockDateTime { get; set; }
        public int StockNumber { get; set; }
        public byte StockType { get; set; }
        public string Remark { get; set; }
        public bool IfDelete { get; set; }
    
        public virtual T_Product T_Product { get; set; }
    }
}
